package view;

import controller.ControllerProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasProdutos;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProdutos;
import model.ModelSessaoFuncionario;
import model.ModelVendas;
import model.ModelVendasProdutos;
import util.BLDatas;
import util.BLMascaras;

/**
 * @author Thiago
 */

public class ViewPDV extends javax.swing.JFrame {
    ControllerProdutos controllerProduto = new ControllerProdutos();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ControllerVendas controllerVendas = new ControllerVendas();
    ModelProdutos modelProduto = new ModelProdutos();
    ModelVendas modelVendas = new ModelVendas();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ModelSessaoFuncionario modelSessaoFuncionario = new ModelSessaoFuncionario();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutos = new ArrayList<>();
    ArrayList<ModelProdutos> listaModelProduto = new ArrayList<>();
    BLDatas blData = new BLDatas();
    int quantidade;
    private ViewPagamentoPDV viewPagamentoPDV;
    private ViewPesquisaProdutos viewPesquisaProdutos;

    /**
     * Creates new form ViewPDV1
     */
    public ViewPDV() {
        initComponents();
        setLocationRelativeTo(null);
        IniciarOperador();
        quantidade = 1;
        this.viewPagamentoPDV = new ViewPagamentoPDV(this, true);
        this.viewPesquisaProdutos = new ViewPesquisaProdutos(this, true);
        LimparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_produtos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        operador = new javax.swing.JLabel();
        status_caixa = new javax.swing.JLabel();
        cod_produto = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Valor_a_Pagar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        desconto = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        excluir = new javax.swing.JMenuItem();
        alterar_quantidade = new javax.swing.JMenuItem();
        finalizar_venda = new javax.swing.JMenuItem();
        pesquisar_produtos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PDV");

        tbl_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Código", "Nome", "Quant.", "Valor Unit.", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_produtos);
        if (tbl_produtos.getColumnModel().getColumnCount() > 0) {
            tbl_produtos.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbl_produtos.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbl_produtos.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbl_produtos.getColumnModel().getColumn(4).setPreferredWidth(10);
            tbl_produtos.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/th (1).jpg"))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Caixa:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Operador:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Status:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("01");

        operador.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        operador.setText("operador");

        status_caixa.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        status_caixa.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operador))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_caixa)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(operador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(status_caixa))
                .addGap(65, 65, 65))
        );

        cod_produto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cod_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cod_produtoKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Comandos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Excluir Item - F2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Alterar Quantidade - F3");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Finalizar Venda - F4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Pesquisar Produtos - F5");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Sair - F6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel5)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Valor a Pagar");

        Valor_a_Pagar.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Valor Total");

        valorTotal.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Desconto");

        desconto.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(desconto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(valorTotal)
                    .addComponent(Valor_a_Pagar))
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Valor_a_Pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivos");

        sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.jpg"))); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Comandos");

        excluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        excluir.setText("Excluir Item");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        jMenu2.add(excluir);

        alterar_quantidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        alterar_quantidade.setText("Alterar Quantidade");
        alterar_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_quantidadeActionPerformed(evt);
            }
        });
        jMenu2.add(alterar_quantidade);

        finalizar_venda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        finalizar_venda.setText("Finalizar Venda");
        finalizar_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizar_vendaActionPerformed(evt);
            }
        });
        jMenu2.add(finalizar_venda);

        pesquisar_produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        pesquisar_produtos.setText("Pesquisar Produtos");
        pesquisar_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar_produtosActionPerformed(evt);
            }
        });
        jMenu2.add(pesquisar_produtos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cod_produto)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
    int QuantLinha = tbl_produtos.getRowCount();
    if(QuantLinha<1){
        JOptionPane.showMessageDialog(this, "Não Há Item Para Ser Excluído","ERRO",JOptionPane.ERROR_MESSAGE);
    }else{
        DefaultTableModel modelo = (DefaultTableModel) tbl_produtos.getModel();
        try{
            int linha = Integer.parseInt(JOptionPane.showInputDialog("Informe o item que deseja excluir"));
            modelo.removeRow(linha-1);
            valorTotal.setText(String.valueOf(ValorTotal()));
                for(int i = 0; i<QuantLinha;i++){
                modelo.setValueAt(i+1, i, 0);
                }
            }catch(NumberFormatException e){    
            }
        }    
    }//GEN-LAST:event_excluirActionPerformed

    private void alterar_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_quantidadeActionPerformed
        // TODO add your handling code here:
        quantidade = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade"));
    }//GEN-LAST:event_alterar_quantidadeActionPerformed

    private void finalizar_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizar_vendaActionPerformed
        // TODO add your handling code here:
        try{
        viewPagamentoPDV.setValorTotal(Float.parseFloat(valorTotal.getText()));
        viewPagamentoPDV.SetTextFieldValorTotal();
        viewPagamentoPDV.setVisible(true);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Você Precisa Preencher os Campos","ERRO",JOptionPane.ERROR_MESSAGE);
        }
        valorTotal.setText(String.valueOf(viewPagamentoPDV.getValorTotal()));
        desconto.setText(String.valueOf(viewPagamentoPDV.getDesconto()));
        Valor_a_Pagar.setText(String.valueOf(viewPagamentoPDV.pagar));
        
        System.out.println(viewPagamentoPDV.getFormaPagamento()); 
        if(viewPagamentoPDV.isConfirmarPagamento()){
        SalvarVenda();
        }else{
            JOptionPane.showMessageDialog(this,"Pagamento Não Efetuado", "ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_finalizar_vendaActionPerformed

    private void pesquisar_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar_produtosActionPerformed
        // TODO add your handling code here:
      viewPesquisaProdutos.setVisible(true);
    }//GEN-LAST:event_pesquisar_produtosActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void cod_produtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cod_produtoKeyReleased
        // TODO add your handling code here:
        InserirConteudo(evt);
    }//GEN-LAST:event_cod_produtoKeyReleased
    
    //limpa os campos após efetuar a venda
    private void LimparCampos(){
        valorTotal.setText("");
        desconto.setText("");
        Valor_a_Pagar.setText("");
        cod_produto.setText("");
        DefaultTableModel modelo = (DefaultTableModel) tbl_produtos.getModel();
        modelo.setNumRows(0);
        status_caixa.setText("Caixa Livre");
    }
    
    private void SalvarVenda(){
        int CodigoProduto=0,CodigoVenda=0;
        modelVendas = new ModelVendas();
        modelVendas.setFk_cliente(6);
        try {
            modelVendas.setData_venda(blData.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(ViewPDV.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        modelVendas.setValor_bruto(Double.parseDouble(valorTotal.getText()));
        modelVendas.setVendas_desconto(viewPagamentoPDV.getDesconto());
        modelVendas.setValor_liquido(Double.parseDouble(Valor_a_Pagar.getText()));
        
        //salvar venda
        CodigoVenda = controllerVendas.salvarVendasController(modelVendas);
        
        int cont = tbl_produtos.getRowCount();
        for(int i=0;i<cont;i++){
            CodigoProduto = (int) tbl_produtos.getValueAt(i, 1);
            modelVendasProdutos = new ModelVendasProdutos();
            modelVendasProdutos.setFk_produto(CodigoProduto);
            modelVendasProdutos.setFk_vendas(CodigoVenda);
            modelVendasProdutos.setValor_vendas_produtos((double) tbl_produtos.getValueAt(i, 4));
            modelVendasProdutos.setVendas_produtos_quantidade(Integer.parseInt(tbl_produtos.getValueAt(i, 3).toString()));
            listaModelVendasProdutos.add(modelVendasProdutos);
            
            //produto
            modelProduto = new ModelProdutos(); 
            modelProduto.setId_produto(CodigoProduto);
            modelProduto.setEstoque_produto(controllerProduto.retornarProdutoController(CodigoProduto).getEstoque_produto()-Integer.parseInt(tbl_produtos.getValueAt(i, 3).toString()));
            listaModelProduto.add(modelProduto);
            }
        
        //salvar os produtos da venda
        if(controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)){
           //alterando o estoque dos produtos
           controllerProduto.alterarEstoqueProdutoController(listaModelProduto);
           JOptionPane.showMessageDialog(this, "Venda Salva com Sucesso","PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
           LimparCampos();
        }else{
           JOptionPane.showMessageDialog(this, "Erro ao Salvar a Venda","ERRO",JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void IniciarOperador(){
        operador.setText(modelSessaoFuncionario.nome);
    }
    
    private float ValorTotal(){
        float soma = 0, valor = 0;
            int cont = tbl_produtos.getRowCount();
            for(int i = 0;i < cont;i++){
            valor = Float.parseFloat(String.valueOf(tbl_produtos.getValueAt(i, 5)));
            soma += valor;
            }
        return soma;
    }
    
    private void InserirConteudo(java.awt.event.KeyEvent e){
        status_caixa.setText("Caixa em Atendimento");
        DefaultTableModel modelo = (DefaultTableModel) tbl_produtos.getModel();
        if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            try{
                modelProduto = controllerProduto.retornarProdutoController(Integer.parseInt(cod_produto.getText()));
            
                modelo.addRow(new Object[]{
                modelo.getRowCount()+1,
                modelProduto.getId_produto(),
                modelProduto.getNome_produto(),
                quantidade,
                modelProduto.getValor_produto(),
                modelProduto.getValor_produto()*quantidade
                });
                valorTotal.setText(String.valueOf(ValorTotal()));
                cod_produto.setText("");
                quantidade = 1;
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Você deve informar apenas números","ERRO",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Valor_a_Pagar;
    private javax.swing.JMenuItem alterar_quantidade;
    private javax.swing.JFormattedTextField cod_produto;
    private javax.swing.JTextField desconto;
    private javax.swing.JMenuItem excluir;
    private javax.swing.JMenuItem finalizar_venda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel operador;
    private javax.swing.JMenuItem pesquisar_produtos;
    private javax.swing.JMenuItem sair;
    private javax.swing.JLabel status_caixa;
    private javax.swing.JTable tbl_produtos;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
