package view;

import javax.swing.JFrame;

/**
 * @author Thiago
 */

public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel1 = new javax.swing.JPanel();
        btn_produtos = new javax.swing.JButton();
        btn_funcionarios = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_vendas = new javax.swing.JButton();
        btn_PDV = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Arq = new javax.swing.JMenu();
        arq_sair = new javax.swing.JMenuItem();
        Menu_Cad = new javax.swing.JMenu();
        cad_cliente = new javax.swing.JMenuItem();
        cad_produto = new javax.swing.JMenuItem();
        cad_func = new javax.swing.JMenuItem();
        Menu_Vendas = new javax.swing.JMenu();
        v_vendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Vendas ");
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Thiago\\Documents\\NetBeansProjects\\ProjetoIntegrador\\src\\imagens\\03a504e3815eece7cb53707a3ea87425.jpg"));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        btn_produtos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        btn_produtos.setText("PRODUTOS");
        btn_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produtosActionPerformed(evt);
            }
        });

        btn_funcionarios.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/th.jpg"))); // NOI18N
        btn_funcionarios.setText("FUNCIONÁRIOS");
        btn_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_funcionariosActionPerformed(evt);
            }
        });

        btn_clientes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.jpg"))); // NOI18N
        btn_clientes.setText("CLIENTES");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        btn_vendas.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        btn_vendas.setText("VENDAS");
        btn_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vendasActionPerformed(evt);
            }
        });

        btn_PDV.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_PDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/istockphoto-1027374334-612x612.jpg"))); // NOI18N
        btn_PDV.setText("PDV");
        btn_PDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_produtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_funcionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_PDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_vendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_PDV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        Menu_Arq.setText("Arquivos");
        Menu_Arq.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        arq_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.jpg"))); // NOI18N
        arq_sair.setText("Sair");
        arq_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arq_sairActionPerformed(evt);
            }
        });
        Menu_Arq.add(arq_sair);

        jMenuBar1.add(Menu_Arq);

        Menu_Cad.setText("Cadastros");
        Menu_Cad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cad_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.jpg"))); // NOI18N
        cad_cliente.setText("Clientes");
        cad_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_clienteActionPerformed(evt);
            }
        });
        Menu_Cad.add(cad_cliente);

        cad_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        cad_produto.setText("Produtos");
        cad_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_produtoActionPerformed(evt);
            }
        });
        Menu_Cad.add(cad_produto);

        cad_func.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/th.jpg"))); // NOI18N
        cad_func.setText("Funcionários");
        cad_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_funcActionPerformed(evt);
            }
        });
        Menu_Cad.add(cad_func);

        jMenuBar1.add(Menu_Cad);

        Menu_Vendas.setText("Vendas");
        Menu_Vendas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        v_vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        v_vendas.setText("Vendas");
        v_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_vendasActionPerformed(evt);
            }
        });
        Menu_Vendas.add(v_vendas);

        jMenuBar1.add(Menu_Vendas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arq_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arq_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_arq_sairActionPerformed

    private void cad_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_clienteActionPerformed
        // TODO add your handling code here:
       ViewCliente cliente = new ViewCliente();
       cliente.setVisible(true);
    }//GEN-LAST:event_cad_clienteActionPerformed

    private void cad_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_produtoActionPerformed
        // TODO add your handling code here:
       ViewProdutos prod = new ViewProdutos();
       prod.setVisible(true);
    }//GEN-LAST:event_cad_produtoActionPerformed

    private void cad_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_funcActionPerformed
        // TODO add your handling code here:
        ViewFuncionario func = new ViewFuncionario();
        func.setVisible(true);
    }//GEN-LAST:event_cad_funcActionPerformed

    private void v_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_vendasActionPerformed
        // TODO add your handling code here:
         ViewVendas vendas = new ViewVendas();
         vendas.setVisible(true);
    }//GEN-LAST:event_v_vendasActionPerformed

    private void btn_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_funcionariosActionPerformed
        // TODO add your handling code here:
        ViewFuncionario func = new ViewFuncionario();
        func.setVisible(true);
    }//GEN-LAST:event_btn_funcionariosActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        // TODO add your handling code here:
       ViewCliente cliente = new ViewCliente();
       cliente.setVisible(true);
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produtosActionPerformed
        // TODO add your handling code here:
       ViewProdutos prod = new ViewProdutos();
       prod.setVisible(true);
    }//GEN-LAST:event_btn_produtosActionPerformed

    private void btn_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vendasActionPerformed
        // TODO add your handling code here:
        ViewVendas vendas = new ViewVendas();
        vendas.setVisible(true);
    }//GEN-LAST:event_btn_vendasActionPerformed

    private void btn_PDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PDVActionPerformed
        // TODO add your handling code here:
        ViewPDV PDV = new ViewPDV();
        PDV.setVisible(true);
    }//GEN-LAST:event_btn_PDVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Arq;
    private javax.swing.JMenu Menu_Cad;
    private javax.swing.JMenu Menu_Vendas;
    private javax.swing.JMenuItem arq_sair;
    private javax.swing.JButton btn_PDV;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_funcionarios;
    private javax.swing.JButton btn_produtos;
    private javax.swing.JButton btn_vendas;
    private javax.swing.JMenuItem cad_cliente;
    private javax.swing.JMenuItem cad_func;
    private javax.swing.JMenuItem cad_produto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private componentes.UJPanelImagem uJPanelImagem1;
    private javax.swing.JMenuItem v_vendas;
    // End of variables declaration//GEN-END:variables
}
