package view;

import controller.ControllerCliente;
import controller.ControllerProdutos;
import controller.ControllerProdutosVendasProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasCliente;
import controller.ControllerVendasProdutos;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelCliente;
import model.ModelProdutos;
import model.ModelProdutosVendasProdutos;
import model.ModelVendasCliente;
import model.ModelVendas;
import model.ModelVendasProdutos;
import util.BLDatas;

/**
 * @author Thiago
 */

public class ViewVendas extends javax.swing.JFrame {
    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ControllerProdutos controllerProduto = new ControllerProdutos();
    ModelProdutos modelProduto = new ModelProdutos();
    ArrayList<ModelCliente> listaModelCliente = new ArrayList<>();
    ArrayList<ModelProdutos> listaModelProduto = new ArrayList<>();
    ArrayList<ModelVendasCliente> listaModelVendasCliente = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    ControllerVendas controllerVendas = new ControllerVendas();
    ModelVendas modelVendas = new ModelVendas();
    BLDatas blDatas = new BLDatas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutos = new ArrayList<>();
    ControllerProdutosVendasProdutos controllerProdutosVendasProdutos = new ControllerProdutosVendasProdutos();
    ModelProdutosVendasProdutos modelProdutosVendasProdutos = new ModelProdutosVendasProdutos();
    ArrayList<ModelProdutosVendasProdutos> listaModelProdutosVendasProdutos = new ArrayList<>();
    String alterarSalvar = "Salvar";
    
    

    /**
     * Creates new form ViewVendas
     */
    
    public ViewVendas() {
        initComponents();
        ListarClientes();
        ListarProdutos();
        ListarVendas();
        PreencherCodigoCliente();
        PreencherCodigoProduto();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cod_cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        num_venda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cod_produto = new javax.swing.JTextField();
        btn_adicionar = new javax.swing.JButton();
        quant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vendas_produtos = new javax.swing.JTable();
        valor_total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        desconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        cb_produto = new componentes.UJComboBox();
        cb_cliente = new componentes.UJComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        c_pesquisar = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_vendas = new javax.swing.JTable();
        btn_excluir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);

        jLabel1.setText("Código Cliente:");

        cod_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cod_clienteFocusLost(evt);
            }
        });

        jLabel2.setText("Nome do Cliente:");

        jLabel3.setText("Número da Venda:");

        num_venda.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setText("Código Produto:");

        cod_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cod_produtoFocusLost(evt);
            }
        });

        btn_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download.jpg"))); // NOI18N
        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade:");

        jLabel6.setText("Nome do Produto:");

        tbl_vendas_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Produto", "Nome Produto", "Quant.", "Valor Unit.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_vendas_produtos);
        if (tbl_vendas_produtos.getColumnModel().getColumnCount() > 0) {
            tbl_vendas_produtos.getColumnModel().getColumn(0).setMinWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(0).setPreferredWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(0).setMaxWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(2).setMinWidth(70);
            tbl_vendas_produtos.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbl_vendas_produtos.getColumnModel().getColumn(2).setMaxWidth(70);
            tbl_vendas_produtos.getColumnModel().getColumn(3).setMinWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(3).setPreferredWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(3).setMaxWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(4).setMinWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbl_vendas_produtos.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        jLabel7.setText("Valor Total:");

        desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                descontoFocusLost(evt);
            }
        });

        jLabel8.setText("Desconto:");

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.jpg"))); // NOI18N
        btn_cancelar.setText("Cancelar");

        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.jpg"))); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exluirproduto.png"))); // NOI18N
        btn_remover.setText("Remover Produtos");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        cb_produto.setAutocompletar(true);
        cb_produto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_produtoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cb_cliente.setAutocompletar(true);
        cb_cliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_clientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cod_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cod_produto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cb_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_adicionar))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valor_total, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7)))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cancelar)
                        .addGap(23, 23, 23)
                        .addComponent(btn_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_remover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salvar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adicionar)
                    .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salvar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_novo)
                        .addComponent(btn_cancelar)
                        .addComponent(btn_remover)))
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel9.setText("Pesquisa:");

        btn_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        tbl_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Nome Cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_vendas);
        if (tbl_vendas.getColumnModel().getColumnCount() > 0) {
            tbl_vendas.getColumnModel().getColumn(0).setMinWidth(110);
            tbl_vendas.getColumnModel().getColumn(0).setPreferredWidth(110);
            tbl_vendas.getColumnModel().getColumn(0).setMaxWidth(110);
            tbl_vendas.getColumnModel().getColumn(2).setMinWidth(110);
            tbl_vendas.getColumnModel().getColumn(2).setPreferredWidth(110);
            tbl_vendas.getColumnModel().getColumn(2).setMaxWidth(110);
        }

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deletar.jpg"))); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.jpg"))); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(c_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pesquisar)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btn_excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_alterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterar)
                    .addComponent(btn_excluir))
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Alterar/Consultar/Excluir", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cod_clienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cod_clienteFocusLost
       //retorna o nome do cliente através do código
        modelCliente = controllerCliente.getClienteController(Integer.parseInt(cod_cliente.getText()));
        cb_cliente.setSelectedItem(modelCliente.getCli_nome());
    }//GEN-LAST:event_cod_clienteFocusLost

    private void cod_produtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cod_produtoFocusLost
        //retorna o nome do cliente através do código
        modelProduto = controllerProduto.retornarProdutoController(Integer.parseInt(cod_produto.getText()));
        cb_produto.setSelectedItem(modelProduto.getNome_produto());
    }//GEN-LAST:event_cod_produtoFocusLost

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        int linha = tbl_vendas.getSelectedRow();
        int CodigoVenda = (int) tbl_vendas.getValueAt(linha,0);
        
        listaModelProduto = new ArrayList<>();
        listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(CodigoVenda);
        
        for(int i=0;i<listaModelProdutosVendasProdutos.size();i++){
           modelProduto = new ModelProdutos();
           modelProduto.setId_produto(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getId_produto());
           modelProduto.setEstoque_produto(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getEstoque_produto() +
           listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVendas_produtos_quantidade());
          listaModelProduto.add(modelProduto);
        }
          if(controllerProduto.alterarEstoqueProdutoController(listaModelProduto)){
              controllerVendasProdutos.excluirVendasProdutosController(CodigoVenda);
              if(controllerVendas.excluirVendasController(CodigoVenda)){
              JOptionPane.showMessageDialog(this, "Venda Excluída com Sucesso","PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
              ListarVendas();
              }else{
              JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda","ERRO",JOptionPane.ERROR_MESSAGE);
              }
          }else{
              JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda","ERRO",JOptionPane.ERROR_MESSAGE);
          }    
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        // TODO add your handling code here:
        if(quant.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Quantidade Não Informada!","ERRO",JOptionPane.ERROR_MESSAGE);
        }else{
            modelProduto = controllerProduto.retornarProdutoController(Integer.parseInt(cod_produto.getText()));
            
            //adicionando uma linha na tabela
            DefaultTableModel model = (DefaultTableModel) tbl_vendas_produtos.getModel();
            int cont = 0;
            
            double quantidade = 0;
            quantidade = Double.parseDouble(quant.getText());
            
            for(int i=0;i<cont;i++){
                model.setNumRows(0);
            }
            
            model.addRow(new Object[]{
            modelProduto.getId_produto(),
            modelProduto.getNome_produto(),
            quant.getText(),
            modelProduto.getValor_produto(),
            quantidade * modelProduto.getValor_produto()
            });
        ValorTotalVenda();
        }
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void descontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descontoFocusLost
        // TODO add your handling code here:
        ValorTotalVenda();
    }//GEN-LAST:event_descontoFocusLost

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        alterarSalvar = "Salvar";
        btn_salvar.setEnabled(true);
        LimparCampos();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        int CodigoVenda = 0,codigoProduto = 0;
        double Desconto = 0;
        
        if(desconto.getText().equals("")){
           Desconto = 0;
        }else{
            Desconto = Double.parseDouble(desconto.getText());
        }
        
          if(!num_venda.getText().equals("")){
          modelVendas.setId_vendas(Integer.parseInt(num_venda.getText()));  
          }  
        
        listaModelVendasProdutos = new ArrayList<>();
        modelVendas.setFk_cliente(Integer.parseInt(cod_cliente.getText()));
        try {
            modelVendas.setData_venda(blDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        }catch(Exception ex){
            Logger.getLogger(ViewVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelVendas.setValor_liquido(Double.parseDouble(valor_total.getText()));
        modelVendas.setValor_bruto(Double.parseDouble(valor_total.getText()) + Desconto);
        modelVendas.setVendas_desconto(Desconto);
        
        // salva
        if(alterarSalvar.equals("Salvar")){
         //salvar venda
        CodigoVenda = controllerVendas.salvarVendasController(modelVendas);
        if(CodigoVenda>0){
          JOptionPane.showMessageDialog(this, "Venda Salva com Sucesso","PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
        }else{
           JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda","ERRO",JOptionPane.ERROR_MESSAGE); 
        }
        int cont = tbl_vendas_produtos.getRowCount();
        for(int i=0;i<cont;i++){
            codigoProduto = (int) tbl_vendas_produtos.getValueAt(i, 0);
            modelVendasProdutos = new ModelVendasProdutos();
            modelVendasProdutos.setFk_produto(codigoProduto);
            modelVendasProdutos.setFk_vendas(CodigoVenda);
            modelVendasProdutos.setValor_vendas_produtos((double) tbl_vendas_produtos.getValueAt(i, 3));
            modelVendasProdutos.setVendas_produtos_quantidade(Integer.parseInt(tbl_vendas_produtos.getValueAt(i, 2).toString()));
            listaModelVendasProdutos.add(modelVendasProdutos);  
        //produto
        modelProduto = new ModelProdutos(); 
        modelProduto.setId_produto(codigoProduto);
        modelProduto.setEstoque_produto(controllerProduto.retornarProdutoController(codigoProduto).getEstoque_produto()-Integer.parseInt(tbl_vendas_produtos.getValueAt(i, 2).toString()));
        listaModelProduto.add(modelProduto);
        }
        //salvar os produtos da venda
        if(controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)){
           //alterando o estoque dos produtos
           controllerProduto.alterarEstoqueProdutoController(listaModelProduto);
           //JOptionPane.showMessageDialog(this, "Produtos da Venda Salvos com Sucesso","PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
           ListarVendas();
           LimparCampos();
        }else{
           JOptionPane.showMessageDialog(this, "Erro ao Salvar os Produtos da Venda","ERRO",JOptionPane.ERROR_MESSAGE); 
        }
        }else{
         //altera
         //retornar para o estoque e excluir produtos da venda
        int linha = tbl_vendas.getSelectedRow();
        try{
            CodigoVenda = (int) tbl_vendas.getValueAt(linha,0);
        }catch(ArrayIndexOutOfBoundsException e){
        }
        
        listaModelProduto = new ArrayList<>();
        listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(CodigoVenda);
        
        for(int i=0;i<listaModelProdutosVendasProdutos.size();i++){
           modelProduto = new ModelProdutos();
           modelProduto.setId_produto(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getId_produto());
           modelProduto.setEstoque_produto(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getEstoque_produto() +
           listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVendas_produtos_quantidade());
           listaModelProduto.add(modelProduto);
        }
         if(controllerProduto.alterarEstoqueProdutoController(listaModelProduto)){
              if(controllerVendasProdutos.excluirVendasProdutosController(CodigoVenda)){   
                //JOptionPane.showMessageDialog(this, "Venda Excluída com Sucesso","PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
                ListarVendas();
              }else{
                JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda","ERRO",JOptionPane.ERROR_MESSAGE);
              }
          }else{
                JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda","ERRO",JOptionPane.ERROR_MESSAGE);
          }
         // fim do método
         
        if(controllerVendas.atualizarVendasController(modelVendas)){
           JOptionPane.showMessageDialog(this, "Venda Alterada com Sucesso", "PARABÉNS", JOptionPane.INFORMATION_MESSAGE);
        }else{
           JOptionPane.showMessageDialog(this, "Erro ao Alterar a Venda","ERRO",JOptionPane.ERROR_MESSAGE);
        } 
            //adicionando produtos na lista para salvar
            int cont = tbl_vendas_produtos.getRowCount();
            for(int i=0;i<cont;i++){
            codigoProduto = (int) tbl_vendas_produtos.getValueAt(i, 0);
            modelVendasProdutos = new ModelVendasProdutos();
            modelVendasProdutos.setFk_produto(codigoProduto);
            modelVendasProdutos.setFk_vendas(CodigoVenda);
            modelVendasProdutos.setValor_vendas_produtos((double) tbl_vendas_produtos.getValueAt(i, 3));
            modelVendasProdutos.setVendas_produtos_quantidade(Integer.parseInt(tbl_vendas_produtos.getValueAt(i, 2).toString()));
            listaModelVendasProdutos.add(modelVendasProdutos);
            
            //produto
            modelProduto = new ModelProdutos(); 
            modelProduto.setId_produto(codigoProduto);
            modelProduto.setEstoque_produto(controllerProduto.retornarProdutoController(codigoProduto).getEstoque_produto()-Integer.parseInt(tbl_vendas_produtos.getValueAt(i, 2).toString()));
            listaModelProduto.add(modelProduto);    
          }
            //salvar os produtos da venda
            if(controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)){
              //JOptionPane.showMessageDialog(this, "Produtos da Venda Salvos com Sucesso","PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
              ListarVendas();
              LimparCampos();
              controllerProduto.alterarEstoqueProdutoController(listaModelProduto);
            }else{
              JOptionPane.showMessageDialog(this, "Erro ao Salvar os Produtos","ERRO",JOptionPane.ERROR_MESSAGE);
            }
        }
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        // TODO add your handling code here:  
        alterarSalvar = "alterar";
        btn_salvar.setEnabled(true);
        
        int linha = tbl_vendas.getSelectedRow();
        int CodigoVenda = (int) tbl_vendas.getValueAt(linha, 0);
        listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(CodigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) tbl_vendas_produtos.getModel();
        modelo.setNumRows(0);
        for(int i=0;i<listaModelProdutosVendasProdutos.size();i++){
          num_venda.setText(String.valueOf(listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getFk_vendas()));
            modelo.addRow(new Object[]{
                listaModelProdutosVendasProdutos.get(i).getModelProdutos().getId_produto(),
                listaModelProdutosVendasProdutos.get(i).getModelProdutos().getNome_produto(),
                listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVendas_produtos_quantidade(),
                listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getValor_vendas_produtos(),
                listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVendas_produtos_quantidade() * listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getValor_vendas_produtos()
            });
        }
    ValorTotalVenda();
    jTabbedPane1.setSelectedIndex(0);
    
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        // TODO add your handling code here:
        int linha = tbl_vendas_produtos.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tbl_vendas_produtos.getModel();
        modelo.removeRow(linha);
        ValorTotalVenda();
    }//GEN-LAST:event_btn_removerActionPerformed

    private void cb_produtoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_produtoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(cb_produto.isVisible()){
            PreencherCodigoProduto();
        }
    }//GEN-LAST:event_cb_produtoPopupMenuWillBecomeInvisible

    private void cb_clientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_clientePopupMenuWillBecomeInvisible

         // retorna o código do cliente através do nome
        if(cb_cliente.isVisible()){
            PreencherCodigoCliente();
        }
    }//GEN-LAST:event_cb_clientePopupMenuWillBecomeInvisible

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.tbl_vendas.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(model);
        this.tbl_vendas.setRowSorter(classificador);
        
        String texto = c_pesquisar.getText();
        
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
        
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void PreencherCodigoCliente(){
        modelCliente = controllerCliente.getClienteController(cb_cliente.getSelectedItem().toString());
        cod_cliente.setText(String.valueOf(modelCliente.getId_cliente()));
    }
    
    private void PreencherCodigoProduto(){
        modelProduto = controllerProduto.retornarProdutoController(cb_produto.getSelectedItem().toString());
        cod_produto.setText(String.valueOf(modelProduto.getId_produto()));
    }
    
    //aplicar desconto ao valor da venda
    private void AplicarDesconto(){
        try{
         valor_total.setText(String.valueOf(Double.parseDouble(valor_total.getText())-Double.parseDouble(desconto.getText())));   
        }catch(NumberFormatException e){
        }
    }
    
    //método que determina o valor total da venda 
    private void ValorTotalVenda(){
     double soma = 0,valor;
     int cont = tbl_vendas_produtos.getRowCount();
        for(int i = 0;i < cont;i++){
            valor = (double) tbl_vendas_produtos.getValueAt(i, 4);
            soma = soma + valor;
        }
    valor_total.setText(String.valueOf(soma));
    AplicarDesconto();
    }
    
    //preenche o ComboBox com os clientes cadastrados 
    private void ListarClientes(){
        listaModelCliente = controllerCliente.getListaClienteController();
        cb_cliente.removeAllItems();
        for(int i=0;i<listaModelCliente.size();i++){
            cb_cliente.addItem(listaModelCliente.get(i).getCli_nome());
        }
    }
    
    private void ListarVendas(){
      DefaultTableModel modelo = (DefaultTableModel) tbl_vendas.getModel();
      listaModelVendasCliente = controllerVendasCliente.getListaVendasClienteController();
      int cont =  listaModelVendasCliente.size();
      modelo.setNumRows(0);
      
      for(int i=0;i<cont;i++){
          modelo.addRow(new Object[]{
          listaModelVendasCliente.get(i).getModelVendas().getId_vendas(),
          listaModelVendasCliente.get(i).getModelCliente().getCli_nome(),
          listaModelVendasCliente.get(i).getModelVendas().getData_venda()
          });
      }
    }
    
    private void LimparCampos(){
        quant.setText("");
        valor_total.setText("");
        desconto.setText("");
         DefaultTableModel modelo = (DefaultTableModel) tbl_vendas_produtos.getModel();
         modelo.setNumRows(0);
    }
    
    //preenche o ComboBox com os produtos cadastrados
    private void ListarProdutos(){
        listaModelProduto = controllerProduto.retornarListaProdutoController();
        cb_produto.removeAllItems();
        for(int i=0;i<listaModelProduto.size();i++){
            cb_produto.addItem(listaModelProduto.get(i).getNome_produto());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_remover;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField c_pesquisar;
    private componentes.UJComboBox cb_cliente;
    private componentes.UJComboBox cb_produto;
    private javax.swing.JTextField cod_cliente;
    private javax.swing.JTextField cod_produto;
    private javax.swing.JTextField desconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField num_venda;
    private javax.swing.JTextField quant;
    private javax.swing.JTable tbl_vendas;
    private javax.swing.JTable tbl_vendas_produtos;
    private javax.swing.JTextField valor_total;
    // End of variables declaration//GEN-END:variables
}
